# GENERATED by scripts/codegen/gen-models.sh from schemas/knowledge-graph.schema.json — DO NOT EDIT.

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict


class Node(TypedDict):
    id: str
    kind: Literal["concept", "entity"]
    label: str
    dimension: NotRequired[str]
    entityType: NotRequired[str]


class Edge(TypedDict):
    source: str
    target: str
    type: str
    via: Literal["relationship", "entity"]
    strength: NotRequired[float | None]


KnowledgeGraphPerTopic = TypedDict(
    "KnowledgeGraphPerTopic",
    {
        "@type": Literal["KnowledgeGraph"],
        "generator": NotRequired[str],
        "nodes": list[Node],
        "edges": list[Edge],
    },
)
