# GENERATED by scripts/codegen/gen-models.sh from schemas/mif-container.schema.json — DO NOT EDIT.

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict


class SourceInstance(TypedDict):
    namespace: str
    corpusUrl: NotRequired[str | None]


class ExportScope(TypedDict):
    type: Literal["full", "incremental", "subset"]
    topic: str
    selector: str | None
    generatedAt: str


class OntologyBinding(TypedDict):
    packId: str
    version: str


class Resource(TypedDict):
    mifType: Literal["finding", "ontology-map", "concordance"]
    path: str
    ontologyType: str | None
    digest: str


class BoundaryReference(TypedDict):
    target: str
    reason: Literal["out-of-scope", "cross-topic", "unresolvable"]


class MifContainerManifestMifPackageJson(TypedDict):
    profile: Literal["https://research-harness.dev/schema/mif-container/v1"]
    sourceInstance: SourceInstance
    exportScope: ExportScope
    ontologyBindings: list[OntologyBinding]
    resources: list[Resource]
    boundaryReferences: list[BoundaryReference]
    manifestDigest: str
    createdAt: str
