#!/usr/bin/env bash
# run-gate-and-publish.sh — continuous-monitoring pipeline orchestrator,
# Phase 2 (research-harness-template#424). Triggered by the review PR
# (Editorial Gate, research-harness-template#422) actually closing: builds
# a whole-batch decisions map from the PR's merged/closed state per
# ADR-0019 ("merging it is the accept path... closing it without merge is
# the reject path"), then runs editorial-gate.sh and output-router.sh.
#
# Usage: run-gate-and-publish.sh <domain-or-topic-id> <run-id> <recommendations.json> <merged: true|false>
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
# shellcheck source=packs/monitoring/continuous-monitor/scripts/lib/continuity-log.sh
. "$SCRIPT_DIR/lib/continuity-log.sh"

SUBJECT="${1:?usage: run-gate-and-publish.sh <domain-or-topic-id> <run-id> <recommendations.json> <merged: true|false>}"
RUN_ID="${2:?missing run-id}"
RECOMMENDATIONS="${3:?missing recommendations.json}"
MERGED="${4:?missing merged (true|false)}"

# Both SUBJECT and RUN_ID are used to build filesystem paths and are, via
# monitor-gate.yml, ultimately derived from a PR's head branch name --
# attacker-influenceable. Reject anything that isn't a bare path segment
# (matches harness.config.schema.json's own topic/domain id patterns; run
# ids are generated by run-monitoring.sh as run-<timestamp>-<github-run-id>,
# same bare-segment shape) before it touches a single path.
case "$SUBJECT" in ""|*/*|*..*) echo "run-gate-and-publish: invalid subject id: $SUBJECT" >&2; exit 2 ;; esac
case "$RUN_ID" in ""|*/*|*..*) echo "run-gate-and-publish: invalid run id: $RUN_ID" >&2; exit 2 ;; esac

# Subject resolution mirrors run-monitoring.sh (#521, #522): a
# monitoringDomains[] id wins, a topic id is the fallback. A domain's
# accepted candidates publish as findings only when the domain binds a
# topic via projectToTopic; a standalone domain's digest IS the
# deliverable, so its Output Router step is deliberately skipped.
CONFIG="${HARNESS_CONFIG:-$ROOT/harness.config.json}"
DOMAIN_CFG="$(jq -c --arg d "$SUBJECT" '(.monitoringDomains // [])[] | select(.id == $d)' "$CONFIG")"
if [ -n "$DOMAIN_CFG" ]; then
  PUBLISH_TOPIC="$(printf '%s' "$DOMAIN_CFG" | jq -r '.projectToTopic // empty')"
elif jq -e --arg t "$SUBJECT" '.topics[] | select(.id == $t)' "$CONFIG" >/dev/null 2>&1; then
  PUBLISH_TOPIC="$SUBJECT"
else
  echo "run-gate-and-publish: '$SUBJECT' is neither a monitoringDomains[] id nor a topic id in harness.config.json" >&2
  exit 2
fi

[ -f "$RECOMMENDATIONS" ] || { echo "run-gate-and-publish: recommendations file not found: $RECOMMENDATIONS" >&2; exit 2; }

DECISION="reject"
[ "$MERGED" = "true" ] && DECISION="accept"

# Whole-batch decision per ADR-0019: every recommendation in the PR gets
# the same accept/reject outcome. editorial-gate.sh's decisions map
# supports per-item decisions too (a future finer-grained review, e.g. one
# decision per PR comment, could populate this differently), but the
# current review granularity is the whole PR.
DECISIONS="$(jq --arg d "$DECISION" 'reduce .[] as $r ({}; .[($r.id // ("gap:" + $r.dimension))] = $d)' "$RECOMMENDATIONS")"
DECISIONS_FILE="$(mktemp).json"
printf '%s' "$DECISIONS" > "$DECISIONS_FILE"

ACCEPTED_FILE="$(monitoring_base_dir "$ROOT" "$SUBJECT")/runs/$RUN_ID/accepted.json"
bash "$SCRIPT_DIR/editorial-gate.sh" "$SUBJECT" "$RUN_ID" "$RECOMMENDATIONS" "$DECISIONS_FILE" "$ACCEPTED_FILE"

ACCEPTED_COUNT="$(jq 'length' "$ACCEPTED_FILE")"
if [ "$ACCEPTED_COUNT" -gt 0 ]; then
  # Prior-coverage memory (#523): the gate-accept path is the memory's ONLY
  # writer (single-writer discipline, per the weekly-research reference) --
  # recommend.py only ever reads it. Written before publish so a publish
  # failure can't lose the acceptance record.
  python3 "$SCRIPT_DIR/lib/recommend.py" coverage-append "$ACCEPTED_FILE" \
    "${MONITOR_PRIOR_COVERAGE:-$ROOT/reports/_monitoring/prior-coverage.jsonl}" "$RUN_ID" >&2

  if [ -n "$PUBLISH_TOPIC" ]; then
    bash "$SCRIPT_DIR/output-router.sh" "$PUBLISH_TOPIC" "$RUN_ID" "$ACCEPTED_FILE"
  else
    echo "run-gate-and-publish[$SUBJECT/$RUN_ID]: standalone domain (no projectToTopic) -- accepted digest recorded, Output Router skipped by design" >&2
  fi
else
  echo "run-gate-and-publish[$SUBJECT/$RUN_ID]: nothing accepted, Output Router skipped" >&2
fi

rm -f "$DECISIONS_FILE"
echo "run-gate-and-publish[$SUBJECT/$RUN_ID]: done (decision=$DECISION, accepted=$ACCEPTED_COUNT)" >&2
