#!/usr/bin/env bash
# author-ontology.sh — when on-demand resolution finds no ontology for a domain,
# scaffold one FROM THE RESEARCH and concierge a PR to the canonical registry.
#
# The harness is a producer, not just a consumer: the entity types a topic's
# findings actually used (reports/<topic>/ontology-map.json) — especially the
# ones that fell back to the generic core — are the raw material for a new
# domain ontology. This drafts that ontology and prepares its contribution.
#
# Usage:
#   author-ontology.sh <new-id> <topic> [--out <file>] [--open-pr]
#   author-ontology.sh <new-id> --from-clusters <clusters.json> [--out <file>] [--open-pr]
#     <new-id>   id for the new ontology (e.g. clinical-trials)
#     <topic>    topic dir under reports/ to mine observed types from
#     --from-clusters  alternate input: instead of mining a topic's
#                ontology-map.json, read `mif-rh-cli expansion-candidates`
#                output (recurring tier-3 misses clustered by similarity; see
#                docs/adr/0015) and scaffold one draft candidate type per
#                cluster, quoting member excerpts and finding ids
#     --out      write the draft here (default: a temp file, path printed)
#     --open-pr  concierge: branch the ontologies repo, drop the draft, open a draft PR
#
# Grounding fields are stubbed TODO on purpose — a human (or a follow-up research
# pass) supplies the cited source vocabulary before the upstream PR merges.
#
# Since research-harness-template#276 (Story #277, Category A cutover),
# the draft itself (mining ontology-map.json or expansion-candidates
# clusters, rendering the ontology YAML) is generated by the mif-rh engine
# (`mif-rh-cli ontology author`), hard required: install it with
# scripts/fetch-engine.sh, put mif-rh-cli on PATH, or set MIF_RH_CLI. This
# script keeps only argument parsing, the next-steps message, and the
# --open-pr concierge step, which orchestrates git/gh directly.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/lib/engine.sh
. "$ROOT/scripts/lib/engine.sh"
ENGINE="$(engine_bin "$ROOT")" || exit 5

NEWID=""; TOPIC=""; OUT=""; OPEN_PR=0; CLUSTERS=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --out) OUT="$2"; shift 2;;
    --open-pr) OPEN_PR=1; shift;;
    --from-clusters) CLUSTERS="$2"; shift 2;;
    -*) echo "author-ontology: unknown flag $1" >&2; exit 2;;
    *) if [ -z "$NEWID" ]; then NEWID="$1"; elif [ -z "$TOPIC" ]; then TOPIC="$1"; fi; shift;;
  esac
done
[ -n "$NEWID" ] && { [ -n "$TOPIC" ] || [ -n "$CLUSTERS" ]; } \
  || { echo "usage: author-ontology.sh <new-id> <topic> [--out f] [--open-pr]" >&2
       echo "       author-ontology.sh <new-id> --from-clusters <clusters.json> [--out f] [--open-pr]" >&2; exit 2; }
# The two input modes are mutually exclusive: silently preferring one would
# leave the other argument doing nothing without any signal.
[ -n "$TOPIC" ] && [ -n "$CLUSTERS" ] \
  && { echo "author-ontology: give either a <topic> or --from-clusters, not both" >&2; exit 2; }

# Validate --from-clusters BEFORE creating a temp dir below: an early exit
# here must not orphan one.
[ -z "$CLUSTERS" ] || [ -f "$CLUSTERS" ] \
  || { echo "author-ontology: no such clusters file: $CLUSTERS" >&2; exit 1; }

# Portable temp: `mktemp -t <template>` is interpreted differently across
# implementations (BSD/BusyBox treat a non-trailing-X template inconsistently).
# `mktemp -d` is portable everywhere; we control the filename inside it.
[ -n "$OUT" ] || { tmpd="$(mktemp -d)" && OUT="$tmpd/$NEWID.ontology.yaml"; } \
  || { echo "author-ontology: mktemp failed" >&2; exit 1; }

if [ -n "$CLUSTERS" ]; then
  # Alternate input: `mif-rh-cli expansion-candidates` output — recorded tier-3
  # misses clustered by mutual similarity (ADR-0015). Each cluster becomes one
  # draft candidate type for a human to name, define, and ground.
  "$ENGINE" ontology author "$NEWID" --from-clusters "$CLUSTERS" --out "$OUT" || exit 1
  # basename only: ORIGIN lands in commit messages and PR bodies via
  # --open-pr, and a local temp path is provenance noise in a public artifact.
  ORIGIN="tier-3 expansion clusters ($(basename "$CLUSTERS"))"
else
  "$ENGINE" ontology author "$NEWID" "$TOPIC" --out "$OUT" || exit 1
  ORIGIN="research topic '$TOPIC'"
fi
ntypes=$(grep -c '^  - name:' "$OUT" || true)
# Defense in depth: the engine itself already fails closed on zero entity
# types/clusters (it errors rather than writing a degenerate draft), but
# --open-pr below concierges a real upstream PR — never proceed into that
# on an empty draft, whatever produced it.
[ "$ntypes" -gt 0 ] || { echo "author-ontology: drafted ontology has 0 entity types — refusing to proceed" >&2; exit 1; }

if [ -n "$CLUSTERS" ]; then
  echo "author-ontology: drafted '$NEWID' with $ntypes candidate type(s) from clusters -> $OUT"
  echo "  (one todo-cluster-N per recurring tier-3 miss cluster — name, define, and ground each before contributing)"
else
  echo "author-ontology: drafted '$NEWID' with $ntypes entity type(s) -> $OUT"
  echo "  (generic-fallback types listed first — those most need a domain home)"
fi

if [ "$OPEN_PR" != 1 ]; then
  cat >&2 <<EOF

Next — contribute it upstream (concierge):
  1. Review/fill the TODO grounding in $OUT
  2. Re-run with --open-pr to branch the ontologies repo, drop the draft, regenerate
     the index, and open a draft PR — or do it by hand:
       cp "$OUT" <ontologies-repo>/ontologies/${NEWID}.ontology.yaml
       (cd <ontologies-repo> && scripts/gen-ontology-index.sh && \\
        git checkout -b feat/ontology-${NEWID} && git add -A && \\
        git commit -m "feat(ontology): add ${NEWID} (drafted from harness ${ORIGIN})" && \\
        gh pr create --draft --title "feat(ontology): ${NEWID}" --body "Drafted from harness ${ORIGIN}.")
EOF
  exit 0
fi

# --- concierge: open the PR (opt-in) ---------------------------------------
ONT_REPO="${MIF_ONTOLOGIES_REPO:-}"
[ -z "$ONT_REPO" ] && [ -d "$ROOT/../ontologies" ] && ONT_REPO="$ROOT/../ontologies"
[ -n "$ONT_REPO" ] && [ -d "$ONT_REPO/ontologies" ] || { echo "author-ontology: set MIF_ONTOLOGIES_REPO to the ontologies repo to --open-pr" >&2; exit 1; }
command -v gh >/dev/null || { echo "author-ontology: gh CLI required for --open-pr" >&2; exit 1; }

branch="feat/ontology-${NEWID}"
cp "$OUT" "$ONT_REPO/ontologies/${NEWID}.ontology.yaml"
( cd "$ONT_REPO" || exit 1
  if [ -x scripts/gen-ontology-index.sh ]; then bash scripts/gen-ontology-index.sh || exit 1; fi
  git checkout -b "$branch" \
  && git add -A \
  && git commit -q -m "feat(ontology): add ${NEWID} (drafted from harness ${ORIGIN})

Scaffolded by the research harness from ${ORIGIN}.
Grounding fields are TODO and must be filled with cited authorities before merge." \
  && git push -u origin "$branch" \
  && gh pr create --draft --title "feat(ontology): ${NEWID} (drafted from research)" \
       --body "Drafted by the research harness from ${ORIGIN}. $([ -n "$CLUSTERS" ] && echo 'Candidate types are recurring tier-3 classification misses clustered by similarity — each needs a real name, definition, and grounding before merge.' || echo "Entity types are the ones the topic's findings actually used (generic-fallback first).") Grounding (source_vocab/source_class/prior_art) is stubbed TODO and needs a cited authority before merge." ) \
  && echo "author-ontology: opened a draft PR for '$NEWID' in $ONT_REPO" \
  || { echo "author-ontology: concierge PR step failed (see output above)" >&2; exit 1; }
