#!/usr/bin/env bash
# gen-models.sh — regenerate the stdlib TypedDict authoring models from the JSON
# Schemas (schemas/*.schema.json). The emitted JSON is the contract; these models
# make agents author it deterministically from typed dicts instead of hand-composed
# shell JSON (no `jq -n` / `eval` quoting footgun).
#
# Pipeline per schema:  bundle (inline $refs offline, no network)  ->  datamodel-codegen
#                       (typing.TypedDict)  ->  lib/harness_models/<name>.py
#
# Runtime stays pure stdlib; datamodel-code-generator is a dev/build-time tool only,
# pinned and installed into a gitignored venv. Generated modules ARE committed.
#
# Usage:  scripts/codegen/gen-models.sh          # regenerate all
#         CHECK=1 scripts/codegen/gen-models.sh  # fail if regeneration would change committed output
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

DCG_VERSION="0.65.0"
# black is datamodel-codegen's formatter and its output is load-bearing for the
# byte-identity the CHECK gate enforces — pin it too, or a new black release would
# reformat the generated modules and fail CI on an unrelated change.
BLACK_VERSION="26.5.1"
VENV="$ROOT/.venv-codegen"
OUT="$ROOT/lib/harness_models"
BUNDLE="$ROOT/scripts/codegen/bundle_schema.py"

# Schemas that agents author as standalone files (each becomes one module).
SCHEMAS=(
  "schemas/findings.schema.json"
  "schemas/goal.schema.json"
  "schemas/artifact.schema.json"
  "schemas/concordance.schema.json"
  "schemas/pack.schema.json"
  "schemas/session-state.schema.json"
  "schemas/mif/ontology.schema.json"
  "schemas/mif/source-envelope.schema.json"
)

# --- toolchain (pinned, isolated) -------------------------------------------
if [ ! -x "$VENV/bin/datamodel-codegen" ] \
   || ! "$VENV/bin/datamodel-codegen" --version 2>/dev/null | grep -q "$DCG_VERSION" \
   || ! "$VENV/bin/black" --version 2>/dev/null | grep -q "$BLACK_VERSION"; then
  echo "==> creating codegen venv (datamodel-code-generator==$DCG_VERSION, black==$BLACK_VERSION)"
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install --quiet --upgrade pip
  "$VENV/bin/pip" install --quiet "datamodel-code-generator==$DCG_VERSION" "black==$BLACK_VERSION"
fi

STAGE="$(mktemp -d)"
CHECK_TMP=""
trap 'rm -rf "$STAGE" "$CHECK_TMP"' EXIT

modname() { # schemas/mif/source-envelope.schema.json -> source_envelope
  basename "$1" | sed 's/\.schema\.json$//; s/-/_/g'
}

DEST="$OUT"
if [ "${CHECK:-0}" = "1" ]; then CHECK_TMP="$(mktemp -d)"; DEST="$CHECK_TMP/harness_models"; fi
mkdir -p "$DEST"

for schema in "${SCHEMAS[@]}"; do
  name="$(modname "$schema")"
  bundled="$STAGE/$name.bundled.json"
  python3 "$BUNDLE" "$schema" "$ROOT/schemas" "$bundled" >/dev/null
  # --no-use-closed-typed-dict keeps the output pure stdlib: without the PEP 728
  # `closed=` kwarg, datamodel-codegen imports TypedDict from `typing`, not the
  # external `typing_extensions`. The closed-object contract
  # (additionalProperties:false) is still enforced by ajv at validation time.
  "$VENV/bin/datamodel-codegen" \
    --input "$bundled" --input-file-type jsonschema \
    --output-model-type typing.TypedDict \
    --target-python-version 3.12 \
    --no-use-closed-typed-dict \
    --formatters black \
    --use-double-quotes \
    --disable-timestamp \
    --custom-file-header "# GENERATED by scripts/codegen/gen-models.sh from $schema — DO NOT EDIT." \
    --output "$DEST/$name.py"
  echo "==> $schema -> lib/harness_models/$name.py"
done

# The package init and emitter are hand-written, never generated; the CHECK diff
# excludes them (and the bytecode cache) so only generated modules are compared.
EXCL=(--exclude='__init__.py' --exclude='emit.py' --exclude='__pycache__')

if [ "${CHECK:-0}" = "1" ]; then
  if ! diff -rq "${EXCL[@]}" "$OUT" "$DEST" >/dev/null; then
    echo "ERROR: generated models are stale — run scripts/codegen/gen-models.sh and commit." >&2
    diff -rq "${EXCL[@]}" "$OUT" "$DEST" || true
    exit 1
  fi
  echo "OK: committed models match a fresh regeneration."
fi
